### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by dr497** [notifi-network/notifi-sdk-ts#46]
The documentation references the wrong NPM package https://notifi-network.github.io/notifi-sdk-ts/#%F0%9F%AA%9D-hook-up-the-sdk

`@notifi/notifi-react-hooks` should be `@notifi-network/notifi-react-hooks`

**Comment by nimesh-notifi** [comment]
committed. Sorry!

**Comment by jennifer-notifi** [comment]
Thank you for the update!
