### ISSUE TITLE
Missing module in notifi-node-sample

### ISSUE THREAD

**Issue by joesixpack** [notifi-network/notifi-sdk-ts#59]
![image](https://user-images.githubusercontent.com/23145642/187747781-84d25e04-7976-48b3-bdaf-d89b172934b3.png)

**Comment by jennifer-notifi** [comment]
Hey @joesixpack Thank you for the advisement, looking into this

**Comment by jennifer-notifi** [comment]
Hey @joesixpack We discovered the following issues below.  We will not be able to get to a fix until early next week - do you need this by? You are also free to help with a fix as well:

- There is a package.json within the node_modulespackages/notifi-node-sample/node_modules/@types/node/package.json with no dependencies
- Either we have to add all dependencies directly into this package.json
- Or we have to remove this package.json and have the sample primarily use packages/notifi-node-sample/package.json

**Comment by jennifer-notifi** [comment]
@joesixpack Checking in if you are still having issues. We have made a few updates and you should be able to run `npm install` and `npm run dev` to test our Node sample.
