### ISSUE TITLE
The field `telegramIds` does not exist on the type `CreateDirectPushAlertInput`.

### ISSUE THREAD

**Issue by baymax-codecare** [notifi-network/notifi-sdk-ts#67]
![image](https://user-images.githubusercontent.com/20901074/193305602-574f35ac-aef4-4d03-91c8-fbaf9c9dbe00.png)

This function doesn't work because telegramIds doesn't exist in CreateDirectPushAlertInput.

![image](https://user-images.githubusercontent.com/20901074/193305529-fa0ca6e7-159e-40ac-929d-8dbada1bc17d.png)

**Comment by jennifer-notifi** [comment]
Hey @baymax-codecare Thank you for reaching out. Let us take a look!

**Comment by jennifer-notifi** [comment]
Hello @baymax-codecare:

Can you please share with us what package and version you are using? 

In `packages/notifi-node/lib/mutations/createDirectPushAlertImpl.ts`, it does look like telegramIds is being passed into the `CreateDirectPushAlertInput` type:

export type CreateDirectPushAlertInput = Readonly<{
 ```
 input: Readonly<{
    userId: string;
    emailAddresses: ReadonlyArray<string>;
    phoneNumbers: ReadonlyArray<string>;
    telegramIds: ReadonlyArray<string>;
  }>;
}>;
```

**Comment by baymax-codecare** [comment]
@notifi-network/notifi-node v0.35.0

**Comment by jennifer-notifi** [comment]
> @notifi-network/notifi-node v0.35.0

Thank you for letting us know. We believe that you are in a Telegram with one of our engineers and he will advise you more on the issue. Please let us know if you're not in the Telegram and we can add you :)

**Comment by baymax-codecare** [comment]
Is Discord possible?

**Comment by jennifer-notifi** [comment]
> Is Discord possible?

@juni-notifi Can you please check if you can connect with @baymax-codecare?

**Comment by baymax-codecare** [comment]
I've sent a request from discord

**Comment by jennifer-notifi** [comment]
@baymax-codecare I would like to check in to see if you were able to resolve this with our dev team. I think that they were talking to your team at Parrot (you're from Parrot, right?)
